// <auto-generated />
using Duannoithat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duannoithat.Migrations
{
    [DbContext(typeof(NoithatDbContext))]
    [Migration("20250624194645_FirstCreate")]
    partial class FirstCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duannoithat.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Phong cách hiện đại phù hợp với nhiều không gian nội thất",
                            ImageUrl = "https://shopdogothachthat.com/pic/Bo-ban-an-6-ghe-go-soi%20(2).jpg",
                            IsTrendingProduct = true,
                            Name = "Bàn Ghế",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Ngồi là êm ngủ là ngon",
                            ImageUrl = "https://noithatdangkhoa.com/wp-content/uploads/2024/06/ghe-sofa-vang-da-phong-khach-sfdk124.jpg",
                            IsTrendingProduct = true,
                            Name = "Ghế Sofa",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Cao su tự nhiên",
                            ImageUrl = "https://nemhana.com/wp-content/uploads/2023/10/dem-thang-loi-cao-su-non-cao-cap.jpg",
                            IsTrendingProduct = true,
                            Name = "Giường",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Tủ đồ phong cách hiện đại",
                            ImageUrl = "https://product.hstatic.net/1000075734/product/tu-quan-ao-canh-lua-cho-phong-ngu-hien-dai-2-1_546ad20e7ef54efa955fc6c5ed4af619_grande.jpg",
                            IsTrendingProduct = true,
                            Name = "Tủ đồ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "kệ sách cổ điển",
                            ImageUrl = "https://api.togihome.vn/storage/images/originals/ke-sach-go-tu-nhien-thiet-ke-nhieu-ngan-sd47-1-idbeaaw8w4zkkyz.webp",
                            IsTrendingProduct = true,
                            Name = "Kệ sách",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Giường gỗ",
                            ImageUrl = "https://dogomanhhung.com/uploads/images/634fc215dfc29f68d57258e0/z3812119525960_9d3fba21753fc64d873dc2fa3fbcece6.jpg",
                            IsTrendingProduct = true,
                            Name = "Giường",
                            Price = 3500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
